version: "3.5"
services:

  config-server:
    image: config-server
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    expose:
      - 9101
    ports:
      - 9101:9101
    
  eureka-server:
    image: eureka-server
    restart: always
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    expose:
      - 9102
    ports:
      - 9102:9102
    depends_on:
      - config-server
    environment:
      spring.cloud.config.uri: http://config-server:9101
      EUREKA_HOST: eureka-server

  pgdb:
    image: postgres:16
    container_name: db-senwata
    hostname: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=senwata
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - 5435:5432/tcp
    volumes:
      - "./pg_db:/var/lib/postgresql/data"

  user-microservice:
    image: user-microservice
    restart: always
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - config-server
      - eureka-server
      - pgdb
    environment:
      spring.cloud.config.uri: http://config-server:9101
      POSTGRES_HOST: pgdb
      POSTGRES_PORT: 5432
      EUREKA_HOST: eureka-server


  